require("neb.options")
require("neb.colorscheme")
require("neb.plugins.treesitter")
require("neb.plugins.direnv")
require("neb.plugins.lualine")
require("neb.plugins.autopairs")
require("neb.plugins.rainbow-delimiters")
require("neb.plugins.triptych")
require("neb.plugins.which-key")
require("neb.plugins.endwise")
require("neb.plugins.barbecue")
require("neb.plugins.conform")
require("neb.plugins.lint")
require("neb.plugins.markdown-toc")
require("neb.plugins.mkdnflow")
require("neb.plugins.markview")
require("neb.plugins.luasnip")

-- NOTE: Lsp
require("neb.plugins.lsp.lsp-zero")
require("neb.plugins.lsp.lspconfig")
require("neb.plugins.lsp.fidget")

-- NOTE: Cmp
require("neb.plugins.cmp")
